# Generated by Django 3.2.9 on 2021-12-06 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clicks.likes'),
        ),
    ]
